version: "3.8"

services:
  springboot_app:
    container_name: amaris_training_01
    build: .
    restart: on-failure
    ports:
      - 3000:8081
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true